pipeline {
  agent any
  parameters {
      gitParameter branchFilter: 'origin/(.*)', defaultValue: 'master', name: 'BRANCH', type: 'PT_BRANCH'
      gitParameter branchFilter: 'origin/(.*)', defaultValue: '0.0.1-SNAPSHOT', name: 'TAG', type: 'PT_TAG',selectedValue: 'TOP'
  }
  stages {
    stage('checkout') {
        steps {
            checkout([$class: 'GitSCM',
                      branches: [[name: 'master']],
                      userRemoteConfigs: [[url: 'git@e.coding.net:muggle0/poseidon/poseidon-service-framework.git']]])
        }
    }
    stage('compile') {
      steps {
         script {
            if (isUnix()) {
             withMaven(jdk:'jdk8',maven: 'maven') {
                sh 'mvn clean install -f ./psf-parent -s ./doc/settings.xml'
             }
            } else {
              withMaven(jdk:'jdk8',maven: 'maven') {
                bat 'mvn clean install -f ./psf-parent -s ./doc/settings.xml'
             }
            }
         }
      }
    }
    stage('tag version') {
        steps {
            script {
                if (isUnix()) {
                    sh "mvn versions:set -DnewVersion=${params.TAG} -f ./psf-parent"
                }else{
                     bat "mvn versions:set -DnewVersion=${params.TAG} -f ./psf-parent"
                }
            }
        }
    }
    stage('deploy') {
        steps {
            script {
               if (isUnix()) {
                withMaven(jdk:'jdk8',maven: 'maven') {
                   sh 'mvn deploy -f ./psf-parent -s ./doc/settings.xml'
                }
               } else {
                 withMaven(jdk:'jdk8',maven: 'maven') {
                   bat 'mvn deploy -f ./psf-parent -s ./doc/settings.xml'
                }
               }
            }
        }
    }
  }
}