pipeline {
  agent any
  stages {
    stage('checkout') {
      steps {
        checkout([$class: 'GitSCM',
        branches: [[name: master]],
        userRemoteConfigs: [[
          url: GIT_REPO_URL,
          credentialsId: CREDENTIALS_ID
        ]]])
      }
    }

    stage('compile and build') {
      steps {
        sh 'mvn clean package deploy -f psf-api-gateway'
      }
    }
  }
}