pipeline {
  agent any
  stages {
    stage('checkout') {
      steps {
        checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'git@github.com:muggle0/poseidon-service-framework.git']])
      }
    }
    stage('compile and build') {
      steps {
        sh 'mvn clean'
      }
    }
  }
}