pipeline {
  agent any
  stages {
    stage('checkout') {
      steps {
        checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'git@e.coding.net:muggle0/poseidon/poseidon-service-framework.git']])
      }
    }
    stage('编译') {
      steps {
        sh 'mvn clean install docker:build -f ./psf-parent -s ./doc/settings.xml'
      }
    }

    stage('push') {
      steps {
         bat 'docker login -u p_znyuan@tencent.com -p Git1977339740! muggle0-docker.pkg.coding.net'
         bat 'docker push'
      }
    }
  }
}