pipeline {
  agent any
  stages {
    stage('checkout') {
      steps {
        checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'git@github.com:muggle0/poseidon-service-framework.git']])
      }
    }
    stage('compile and build') {
      steps {
        withMaven(maven: 'Maven_Installation_Name') {
            sh 'mvn clean package deploy -f ./psf-api-gateway'
        }
      }
    }
  }
}